[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Solidity
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1

# Fuzzing
fuzz_runs = 512
max_test_rejects = 100000

via_ir = true
verbosity = 2

[profile.default.fuzz]
max_str_len = 32

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
